#:schema node_modules/wrangler/config-schema.json
name = "dingyue-worker"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "ecd980cc8f3f4890ad70acbded60d4e5" }
]

[assets]
directory = "./public"
